[package]
name = "framefinery-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories = ["multimedia::video", "multimedia::encoding", "encoding"]
description = "Core media primitives for FrameFinery."
documentation = "https://docs.rs/framefinery-core"

[features]
default = ["product-filters"]
product-filters = ["filter-pattern", "filter-identity", "filter-crop", "filter-scale"]
all-filters = ["product-filters"]
filter-pattern = []
filter-identity = []
filter-crop = []
filter-scale = []

[lib]
name = "framefinery_core"
path = "src/lib.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
