#[cfg(test)]
fn av2_black_444_closed_loop_key_header_payload() -> Av2SyntaxPayload {
    av2_mvp_444_closed_loop_key_header_payload(
        false,
        false,
        &Av2TileLayout::for_geometry(Av2VideoGeometry {
            width: 64,
            height: 64,
        }),
        Av2StreamFormat::yuv444_8(),
        Av2QuantizationParams::lossless(),
    )
}

fn av2_mvp_444_closed_loop_key_header_payload(
    allow_screen_content_tools: bool,
    allow_intrabc: bool,
    tile_layout: &Av2TileLayout,
    stream_format: Av2StreamFormat,
    quantization: Av2QuantizationParams,
) -> Av2SyntaxPayload {
    av2_mvp_444_closed_loop_key_header_payload_with_mode(
        allow_screen_content_tools,
        allow_intrabc,
        tile_layout,
        stream_format,
        quantization,
        true,
        0,
    )
}

fn av2_mvp_444_predictive_closed_loop_key_header_payload(
    allow_screen_content_tools: bool,
    allow_intrabc: bool,
    tile_layout: &Av2TileLayout,
    stream_format: Av2StreamFormat,
    quantization: Av2QuantizationParams,
    order_hint: u16,
) -> Av2SyntaxPayload {
    av2_mvp_444_closed_loop_key_header_payload_with_mode(
        allow_screen_content_tools,
        allow_intrabc,
        tile_layout,
        stream_format,
        quantization,
        false,
        order_hint,
    )
}

fn av2_mvp_444_closed_loop_key_header_payload_with_mode(
    allow_screen_content_tools: bool,
    allow_intrabc: bool,
    tile_layout: &Av2TileLayout,
    stream_format: Av2StreamFormat,
    quantization: Av2QuantizationParams,
    single_picture_header: bool,
    order_hint: u16,
) -> Av2SyntaxPayload {
    let profile = Av2Black444MvpProfile::current();
    let mut writer = Av2SyntaxWriter::new();

    // AV2 v1.0.0 tile_group_obu() for an OBU_CLOSED_LOOP_KEY.
    // The uncompressed header follows AVM write_tilegroup_header() and
    // write_uncompressed_header(). The tile entropy payload is generated by
    // the AV2 range writer below. FrameFinery fixes the current MVP to uniform
    // 64x64 superblock tiles and 8x8 coding leaves; each tile resets the local
    // syntax contexts so no prediction state crosses superblock boundaries.
    writer.write_flag("tile_group.first_tile_group_in_frame", true);
    writer.write_uvlc("uncompressed_header.cur_mfh_id", 0);
    writer.write_uvlc("uncompressed_header.seq_header_id", 0);
    if !single_picture_header {
        writer.write_flag("uncompressed_header.immediate_output_picture", true);
        writer.write_flag("uncompressed_header.frame_size_override_flag", false);
        writer.write_literal(
            "uncompressed_header.order_hint",
            u64::from(order_hint),
            AV2_PREDICTIVE_ORDER_HINT_BITS,
        );
    }
    writer.write_flag(
        "uncompressed_header.allow_screen_content_tools",
        allow_screen_content_tools,
    );
    if allow_screen_content_tools {
        // AV2 v1.0.0 is_intraBC_bv_precision_active(): forcing integer
        // precision suppresses the optional intrabc_bv_precision symbol for
        // intrabc_mode=0. Keep this tied to the current local-IBC path so
        // non-IBC screen-content frames retain their previous header.
        writer.write_flag(
            "uncompressed_header.cur_frame_force_integer_mv",
            allow_intrabc,
        );
    }
    writer.write_flag("uncompressed_header.allow_intrabc", allow_intrabc);
    if allow_intrabc {
        // AV2 v1.0.0 read_intrabc_params(): key frames signal global/local
        // availability after allow_intrabc. FrameFinery's first IBC path is
        // local to the current 64x64 tile, so allow_global_intrabc is false
        // and allow_local_intrabc is inferred true by AVM.
        writer.write_flag("uncompressed_header.allow_global_intrabc", false);
    }
    writer.write_flag(
        "uncompressed_header.disable_cdf_update",
        profile.disable_cdf_update,
    );
    write_mvp_tile_info(&mut writer, tile_layout);
    write_av2_quantization_params(&mut writer, stream_format, quantization);
    writer.write_flag("segmentation.enabled", false);
    write_av2_quantization_matrix_params(&mut writer, quantization);
    write_av2_delta_q_params(&mut writer, quantization);
    write_av2_post_quantization_frame_tools(&mut writer, quantization);
    if !tile_layout.is_single_tile() {
        // AV2 v1.0.0 tile_group_obu(): a single tile group covering all tiles
        // still emits tile_start_and_end_present_flag when tiles_log2 > 0.
        // AVM write_tilegroup_header() packs this immediately after
        // write_uncompressed_header(); the tile-group header byte count is
        // rounded up only after this flag has been written.
        writer.write_flag("tile_group.tile_start_and_end_present_flag", false);
    }
    writer.byte_align_zero("tile_group.header_byte_alignment");

    writer.finish()
}

fn write_av2_quantization_params(
    writer: &mut Av2SyntaxWriter,
    stream_format: Av2StreamFormat,
    quantization: Av2QuantizationParams,
) {
    debug_assert!(quantization.base_qindex <= av2_max_qindex(stream_format.bit_depth));
    writer.write_literal(
        "quantization.base_qindex",
        u64::from(quantization.base_qindex),
        av2_qindex_bits(stream_format.bit_depth),
    );
}

fn write_av2_quantization_matrix_params(
    writer: &mut Av2SyntaxWriter,
    quantization: Av2QuantizationParams,
) {
    writer.write_flag(
        "quantization_matrix.using_qmatrix",
        quantization.using_qmatrix,
    );
}

fn write_av2_delta_q_params(writer: &mut Av2SyntaxWriter, quantization: Av2QuantizationParams) {
    if quantization.base_qindex == 0 {
        debug_assert!(!quantization.delta_q.present);
        return;
    }
    writer.write_flag("delta_q.present", quantization.delta_q.present);
    if quantization.delta_q.present {
        // TODO(av2-lossy): enable this after regular lossy coefficient coding
        // tracks and emits per-SB qindex changes.
        debug_assert!(quantization.delta_q.resolution_log2 <= 2);
        writer.write_literal(
            "delta_q.resolution_log2",
            u64::from(quantization.delta_q.resolution_log2),
            2,
        );
    }
}

fn write_av2_post_quantization_frame_tools(
    writer: &mut Av2SyntaxWriter,
    quantization: Av2QuantizationParams,
) {
    if !quantization.is_coded_lossless() {
        writer.write_flag("loop_filter.apply_deblocking_filter_y_vertical", false);
        writer.write_flag("loop_filter.apply_deblocking_filter_y_horizontal", false);
        writer.write_flag("uncompressed_header.tx_mode_select", true);
    }
    writer.write_literal(
        "uncompressed_header.reduced_tx_set_used",
        if quantization.is_coded_lossless() {
            0
        } else {
            2
        },
        2,
    );
}

fn write_mvp_tile_info(writer: &mut Av2SyntaxWriter, tile_layout: &Av2TileLayout) {
    writer.write_flag("tile_info.uniform_spacing_flag", true);
    write_uniform_tile_log2(
        writer,
        "tile_info.increment_log2_cols",
        "tile_info.stop_log2_cols",
        tile_layout.min_log2_cols,
        tile_layout.log2_cols,
        tile_layout.max_log2_cols,
    );
    write_uniform_tile_log2(
        writer,
        "tile_info.increment_log2_rows",
        "tile_info.stop_log2_rows",
        tile_layout.min_log2_rows,
        tile_layout.log2_rows,
        tile_layout.max_log2_rows,
    );
    if !tile_layout.is_single_tile() {
        writer.write_literal(
            "tile_info.tile_size_bytes_minus1",
            (AV2_TILE_SIZE_BYTES - 1) as u64,
            2,
        );
    }
}

fn write_uniform_tile_log2(
    writer: &mut Av2SyntaxWriter,
    increment_name: &'static str,
    stop_name: &'static str,
    min_log2: u8,
    target_log2: u8,
    max_log2: u8,
) {
    assert!(min_log2 <= target_log2);
    assert!(target_log2 <= max_log2);
    for _ in min_log2..target_log2 {
        writer.write_flag(increment_name, true);
    }
    if target_log2 < max_log2 {
        writer.write_flag(stop_name, false);
    }
}



fn av2_mvp_regular_inter_header_payload(
    tile_layout: &Av2TileLayout,
    stream_format: Av2StreamFormat,
    quantization: Av2QuantizationParams,
    order_hint: u16,
) -> Av2SyntaxPayload {
    let profile = Av2Black444MvpProfile::current();
    let mut writer = Av2SyntaxWriter::new();

    writer.write_flag("tile_group.first_tile_group_in_frame", true);
    writer.write_uvlc("uncompressed_header.cur_mfh_id", 0);
    writer.write_uvlc("uncompressed_header.seq_header_id", 0);
    writer.write_flag("uncompressed_header.is_inter_frame", true);
    writer.write_flag("uncompressed_header.immediate_output_picture", true);
    writer.write_flag("uncompressed_header.frame_size_override_flag", false);
    writer.write_literal(
        "uncompressed_header.order_hint",
        u64::from(order_hint),
        AV2_PREDICTIVE_ORDER_HINT_BITS,
    );
    writer.write_flag("uncompressed_header.signal_primary_ref_frame", false);
    writer.write_flag("uncompressed_header.cross_frame_context_disabled", true);
    writer.write_literal("uncompressed_header.refresh_frame_flags", 1, 2);
    writer.write_flag("uncompressed_header.allow_screen_content_tools", true);
    writer.write_flag("uncompressed_header.cur_frame_force_integer_mv", true);
    writer.write_flag("uncompressed_header.allow_intrabc", false);
    writer.write_flag("uncompressed_header.frame_interp_filter_switchable", false);
    writer.write_literal("uncompressed_header.frame_interp_filter", 0, 2);
    writer.write_flag(
        "uncompressed_header.disable_cdf_update",
        profile.disable_cdf_update,
    );
    write_mvp_tile_info(&mut writer, tile_layout);
    write_av2_quantization_params(&mut writer, stream_format, quantization);
    writer.write_flag("segmentation.enabled", false);
    write_av2_quantization_matrix_params(&mut writer, quantization);
    write_av2_delta_q_params(&mut writer, quantization);
    if !quantization.is_coded_lossless() {
        writer.write_flag("loop_filter.apply_deblocking_filter_y_vertical", false);
        writer.write_flag("loop_filter.apply_deblocking_filter_y_horizontal", false);
        writer.write_flag("uncompressed_header.tx_mode_select", true);
    }
    writer.write_flag("uncompressed_header.reference_mode_select", false);
    writer.write_flag("uncompressed_header.skip_mode_flag", false);
    writer.write_literal(
        "uncompressed_header.reduced_tx_set_used",
        if quantization.is_coded_lossless() {
            0
        } else {
            2
        },
        2,
    );
    if !tile_layout.is_single_tile() {
        writer.write_flag("tile_group.tile_start_and_end_present_flag", false);
    }
    writer.byte_align_zero("tile_group.header_byte_alignment");

    writer.finish()
}
